pipeline:
  build:
    image: python:3.6
    commands:
      - python test_hello.py
  publish:
    image: chriswood123/hello-drone:latest
    dockerfile: Dockerfile.drone
    when:
      branch: master
  test_new_version:
    image: chriswood123/hello-drone:latest
    hello: test
